### ISSUE TITLE
Context menu "Open link in new window" sometimes opens a new tab instead

### ISSUE THREAD

**Issue by RossPatterson** [ChaosinaCan/ClassicTabs#17]
With this extension installed, the standard Opera context menu "Open link in new window" command sometimes opens a new tab instead.  The new window opens very briefly, then closes, and the tab appears in the original window.  This doesn't happen often or predictably - most of the time, the command opens a new window and the tab stays there.  

My options are set to "When opening a tab: Open all tabs at the end of the tab bar", "When closing a tab: Activate the last active tab", and "When opening a link in a new tab: Let the browser decide and Shift+click opens tabs in the same window".

**Comment by ChaosinaCan** [comment]
And you're definitely not holding Shift when this happens? Do you know if you were holding Shift at some point before seeing this happen?

Since the extension code which detects whether Ctrl and Shift are pressed cannot run on internal Opera pages (speed dial, bookmarks, settings, etc.), it's also possible Shift could get stuck down if you were holding it while switching to one of those tabs. For instance, I can reproduce this if I hold Shift while clicking the new tab button, then go to any web page and open a link in a new window. Pressing and releasing Shift again while not on an internal page will reset the key state and fix the problem.

**Comment by RossPatterson** [comment]
That's a good question and a good point.  I'll pay close attention when using the extension and see if I can characterize it better.  Most of the time, I'm opening links from my own not-quite-a-bookmark-list HTML file (file:///C:/blah/blah/blah.html) that have target="_blank" to automatically open them in new tab, but occasionally I right-click etc. to open them in a separate window.  But anyway, I'll work on a better problem report and check back when I have one.

**Comment by ChaosinaCan** [comment]
In that case, make sure you've checked "Allow access to file URLs" for Classic Tabs in Opera's extensions page. Otherwise you'll have the same issues I mentioned with both internal pages and your local HTML files.
