### ISSUE TITLE
Cannot display extension settings

### ISSUE THREAD

**Issue by zdenekvecera** [ChaosinaCan/ClassicTabs#38]
Hi,

there are two buttons in the extension list in new Opera 60.0.3255.27 (stable).

![2019-04-10_224232](https://user-images.githubusercontent.com/484387/55912120-59de7b00-5be2-11e9-8100-553dcc0345d3.png)

Both buttons display the same page (extension information). Cannot display extension settings.

![2019-04-10_224226](https://user-images.githubusercontent.com/484387/55912119-5945e480-5be2-11e9-8605-60bd1630c93a.png)

ClassicTabs 2.0 RC
Windows 10 64bit 

Thanks!

**Comment by ChaosinaCan** [comment]
This appears to be a bug in Opera itself. After updating to Opera 60, I am unable to open _any_ extension's settings.

**Comment by zdenekvecera** [comment]
Hi, are you sure no one really? The second button ("Volby") works with these extensions:

- EditThisCookie
- Hootsuite Hootlet
- Image Size Info
- JSONView
- LastPass: Free Password Manager
- Looper for YouTube
- Rotate Images
- Translator

Opera: 60.0.3255.84 stable

Thanks.

**Comment by ChaosinaCan** [comment]
I've figured out what the bug is. It's still on Opera to fix, but I did find a workaround.

An extension can specify that its options page should be opened in a separate tab, inline in the extensions page, or either. If an extension says its options can be inline in the extensions page, Opera won't let you access them at all.

**Comment by ChaosinaCan** [comment]
https://github.com/ChaosinaCan/ClassicTabs/releases/tag/v2.0.1-rc.0 should fix this.

**Comment by zdenekvecera** [comment]
Great, it works. Thank you very much!
