### ISSUE TITLE
New permissions required to update

### ISSUE THREAD

**Issue by ghost** [ChaosinaCan/ClassicTabs#44]
Not _per se_ an issue, but a few days ago, Opera started asking me to confirm new permissions in order to update ClassicTabs. These are "Read and change all your data on the websites you visit" and "Modify data you copy and paste".
Would it be possible to explain why these permissions are necessary? Thank you.

**Comment by joelspadin** [comment]
Those permissions appear to refer to `<all_urls>` and `clipboardWrite` from https://github.com/ChaosinaCan/ClassicTabs/blob/824dbbc6d2e823d647bc299b6b4b119e55f4fbfd/app/manifest.json#L46-L51

It's been a long time since I made those change, so I don't remember the exact reasons (Opera waited over a year to publish that version), but I believe `<all_urls>` is needed so https://github.com/ChaosinaCan/ClassicTabs/blob/master/app/scripts/contentscript_chrome.ts can run in every tab. It just tracks whether or not you're holding Ctrl and Shift.

`clipboardWrite` allows the use of `document.execCommand('copy')` here, which lets you copy the extension's logs by clicking a button: https://github.com/ChaosinaCan/ClassicTabs/blob/824dbbc6d2e823d647bc299b6b4b119e55f4fbfd/app/scripts/components/LogViewer.tsx#L31-L36

**Comment by ghost** [comment]
Thank you for the fast response and clarification!
